### ISSUE TITLE
Some plots not working or have unexpected behavior

### ISSUE THREAD

**Issue by jjustison** [KlausVigo/tanggle#5]
Hello,

I have been playing around with plotting network on the package a bit and ran into a few issues when trying to plot some simulated networks . First I've been simulating networks with the following code:
```
##library(devtools)
##devtools::install_github("jjustison/SiPhyNetwork")
library(SiPhyNetwork)


set.seed(1013)
##Simulate a network up to age 2
age_nets <-sim.bdh.age(age=2,numbsim=40,
                       lambda=1,mu=0.2,
                       nu=0.3, hybprops = c(0.5,0.3,0.2),
                       hyb.inher.fxn = make.beta.draw(1,1))
```
This simulates  40 networks. The first odd behavior I found was that I get different plots depending on whether I plot the simulated objects or first write the networks to newick, reread them in, and then plot them. For example:

```
age_net<-age_nets[[74]]
ggevonet(age_net)+geom_tiplab()

newick<-write.evonet(age_net)
read_net<-read.evonet(text=newick)
ggevonet(read_net)+geom_tiplab()+geom_nodelab()
```
This gave me the following plots, respectively:
![image](https://user-images.githubusercontent.com/19258474/137031996-cd53992e-0d21-4d17-8665-23ea83cf6599.png)
![image](https://user-images.githubusercontent.com/19258474/137032051-925f5633-d57d-4cde-b846-96254c2cd8d2.png)

In particular, the hybridization at MRCA(t3,t4) doesn't plot well. It looks like the dashed line is plotting underneath the other line that goes to this node. Is this just an issue with nodes being shuffled around and different hybrid edges being considered when being written to newick? If so, is there a good way to rotate the network such that it doesn't do this? 

Also When I try plotting `age_nets[[33]]`, it crashes R. I wrote the simulation functions to generate these networks so the issue may be that I save the networks as `evonet` objects in some nonstandard way but they seem correct as using `plot(age_net[[33]])` seems to make a reasonable network.

![image](https://user-images.githubusercontent.com/19258474/137033519-69fae206-e271-4345-b9a2-2d1170a2fbea.png)

**Comment by jjustison** [comment]
The plotting function also doesn't seem to like cases where the edge after a hybrid node is the minor hybrid edge of another hybrid node. This happens in the case of  `age_nets[[5]]`. In some cases it is possible to avoid error by switching which edge is the minor edge within the `evonet` object but in the case where both edges leading into a hybrid edge are children of hybrid nodes (figure to illustrate this mouthful), it is unavoidable.

![image](https://user-images.githubusercontent.com/19258474/137035508-224ace44-6cb0-420d-a181-537a1b80d33b.png)

**Comment by KlausVigo** [comment]
Hi @jjustison, 
thanks for opening the issues. 
When plotting the networks the ordering of the `age_net$net` matrix is important. Unfortunately `ggevonet` assumed a certain order, but did not check for it. I just pushed a small change, just making sure the order is right. `reorder(age_net)` will have the same effect. With this change `age_net` and `read_net` will often look identical. 
There is an argument `min_crossing = TRUE` which tries to minimize the number of crossings of edges by sister clades. This sometimes improves appearance of the network, but seems to cause the crash of `age_nets[[33]]`, so you can set it to FALSE and it should run. I will look into this more closely.
